### PR TITLE
Wrap ProfileService studio check in coroutine

### PR DESCRIPTION
**Pull request by joritochip**
ProfileService makes a datastore call when initializing which causes the metamethod to yield. Although this only occurs in studio, it causes the entire framework to break. Wrapping the call in a coroutine fixed the issue.

### CODE REVIEW

**Comment by OverHash** [comment]
What do you mean it yields during the metamethod? ProfileService should probably be enabled as a standalone module.

**Comment by joritochip** [comment]
The Standalone setting that is provided does not change the fact that the module is required inside of a metamethod. Here is the function that loads modules: 
https://github.com/Sleitnick/AeroGameFramework/blob/43e7f969b87ce0aacca1db0f200a0578df12383c/src/ServerScriptService/Aero/Internal/AeroServer.server.lua#L177

**Comment by OverHash** [comment]
I feel as though this PR should be in the ProfileService module, as the problem resignates with the module.

**Comment by Sleitnick** [comment]
I think this might actually be more of an issue with the `WrapModule` method. The fact that it prevents yielding within `Start` is concerning. The whole point of `Start` being executed asynchronously is to allow yielding.

**Comment by MrBob101** [comment]
Any update on this? We had to manually update our ProfileService file but this could confuse new users.

**Comment by Sleitnick** [comment]
Thanks for the PR. I decided to also update to latest ProfileService and made sure to include the `coroutine.wrap()` section. Done within https://github.com/Sleitnick/AeroGameFramework/pull/206

**Pull request closed without merging**
