### PR TITLE
Events shared across modules. Client and Server share respective events across their modules.

### PR DESCRIPTION
**Pull request by jeremy-wilson**
Moved _events and _clientEvents to AeroServer and assigned the reference of those two props to both services and lazily loaded modules so framework events can be available across the board.

### CODE REVIEW

**Comment by Sleitnick** [comment]
The problem that arises here is event naming conflicts. If `Service1` has an event named "Changed", and `Service2` tries to register an event with the same name, then `Service1`s event will be overridden. Having them scoped on the framework also adds unnecessary redundancy, since services are already exposed on the framework.

Another problem that arises is dealing with objects that can be instantiated. Each object would start overriding the events of other objects.

I think a change that needs to be made is to strip access from modules/shared from registering events. They should only be exposed to the Services, Modules, and Shared tables.

But this also brings up another large issue on the framework, which is properly handling the creation and management of events. Right now it is messy confusing. Ideally there shouldn't be helper methods (e.g. `RegisterEvent` and `FireEvent`), but rather an easy way to instantiate events. This would create more consistency between the framework's API and Roblox's standard API for events.

**Comment by jeremy-wilson** [comment]
Problem 1 is just bad design though. Like I said in my other post, having FOO_BAR in one place should be the same event as FOO_BAR in another place within the application, unless you are doing something like Microservices where it doesn't really matter. But Roblox is one big monolith. And if I declare that event FOO_BAR means something, then that should be treated the same across the board.

But under the current framework design, it doesn't matter anyway, because the only place you can use the framework event handlers is in services anyway. People have to use Event.new in order to use events other than that, or manually craft them otherwise.

I am using these code changes in Instance.new modules and I create dynamic events. Meaning, each Instance.new carries a unique event. My parts have unique identifiers on them, and I use those unique identifiers to create dynamic events. Other Instances then can also listen for these unique events as well. With a proper design, its not a problem.

If the framework stops providing a dictionary for events, like it does now, I would just end up creating my own in order to support it. Under a proper design, it works absolutely fabulously. 

One thing that can be done with the Aero event dictionary, is when we call RegisterEvent, we can error() when an existing event is already registered. I didn't think of that because I am using an external Shared.EventRegistry, but with the changes I proposed, it would be necessary to add it into the client and the server register events.

Perhaps this needs to be a bit more idiot proof, but I am using the framework where modules, services and etc all work together and exchange a lot of data using events. For this reason, events need to mean the same thing across the board. I develop event driven systems in RL, so I apply these conventions to what I am doing in Roblox. Your framework is helping me do that! Yay 👍

**Comment by jeremy-wilson** [comment]
So, I have had this in use for about a week now, and I would have to say that without it, I would not be able to do certain things. As an example, I have a weather system. It runs the day/night cycles as well as fog, rain and clear skies, etc. Most of my parts in the game are dynamic and destructible. I have many parts which need to respond to environment changes. So, as you can imagine, I have a lot of different modules and scripts that all need to listen to weather events, both on the server side as well as the client, so I can do things like turn on/off lights, put a cloud above the player that rain comes out of, add effects, etc. If I did not have a common dictionary to rely on between my services, modules, controllers and shared, then I would not be able to manage events across those scripts as easy as I can now. And using `Shared.Event.new()` is not an option as I would have to implement my own global dictionary outside the framework in order to accomplish this, and I would end up never using the framework provided event structure.

I also implemented `Shared.EventRegistry.new()` which is a singleton that allows me to register events with a common name like `MY_EVENT` and the value is a GUID generated from the http service. So while my code is able to use `MY_EVENT`, the framework sees a GUID as the event name. Both the client and the server are able to lookup events with the shared module, and I am able to simply change the value in the `EventRegistry` instead of having to refactor code when I want to change an event name the framework sees.

So when I manage events, I run code like:

```lua
self:RegisterEvent(self.EventRegistry:GetEvent("WEATHER_PERIOD_DAY_EVENT"))

self:ConnectEvent(self.EventRegistry:GetEvent("WEATHER_PERIOD_DAY_EVENT"), function()
  self:__OnNewDayPeriod()
  self:FireAllClientsEvent(self.EventRegistry:GetEvent("WEATHER_PERIOD_DAY_EVENT"))
end)
```

I still do have the need and desire to have simple events which don't need to be available in other modules. But for these events, I just use `Shared.Event.new()` to manage the event within the script it is intended for. Which I think is the appropriate use case for using `Shared.Event.new()`
 vs the framework events.

The one main problem with this pull request, is if it is accepted, anyone that has been loose with their event names and are running duplicate events all throughout their code, would obviously have problems when they go to update the framework. It is a BC break, so that is problematic. Its unfortunate the plugin does not have a way to warn users that a particular update may break their implementation when the major version is bumped. Maybe the updater can be modified, so if it sees a major version bump, can an issue the user a warning before it goes and updates.

**Comment by jeremy-wilson** [comment]
I merged the most recent `master` changed with these proposed changed. I also combined the two separate client/server pull requests into a single one since they are treating the same issue.

**Comment by Sleitnick** [comment]
In order to keep the framework's setup more consistent with the standards within the Roblox APIs, I am going to continue to keep events isolated to each instance, rather than shared. This consistency will also allow the framework to be more approachable for newer developers who are already familiar with the standard APIs.

**Pull request closed without merging**
