### PR TITLE
Added Mouse:SetMouseIcon(iconId)

### PR DESCRIPTION
**Pull request by Rocky28447**
For allowing change of the mouse icon (duh).

### CODE REVIEW

**Comment by Rocky28447** [comment]
Adjusted code accordingly.

**Comment by Rocky28447** [comment]
Do I have to create a new pull request after changing the code? Not super familiar with how this stuff works.

**Comment by Sleitnick** [comment]
Nope, it is included in this same pull request

**Comment by Sleitnick** [comment]
I'm going to accept this pull request, but I'm going to make a little change to it just for the sake of styling consistency across the framework. Thanks for the pull request!

**Comment by Sleitnick** [comment]
Never mind, you made the changes to match consistency. I'm just going to add the tab back instead of spaces.

**Comment by Rocky28447** [comment]
Oops! My mistake. When I copied in your code it must have copied as spaces.

**Pull request merged**
