### PR TITLE
Update Easing.lua

### PR DESCRIPTION
**Pull request by howmanysmall**
Bezier curves and optimizations

### CODE REVIEW

**Comment by howmanysmall** [comment]
Actually, multiplying isn't faster in Lua. [It's about equal or worse.](https://twitter.com/BoatbomberRBLX/status/1030579032088346630)

I changed a lot of the functions to run faster, take for example the Spring and SoftSpring functions.
image
image

I also added a module to create Bezier curves, while adding some curves from material design specifications as well as some of Microsoft's.

**Comment by Sleitnick** [comment]
I don't think the bezier curve code belongs in this module. Also, the new Lua VM should make caching functions unnecessary. Is there licensing info for Microsoft's stuff?

Regarding multiplying/dividing, multiplying certainly used to be much faster. However, that doesn't seem to be the case anymore. Regardless, I think the performance difference is too minuscule to justify the change.

**Comment by howmanysmall** [comment]
Yeah, it should be in a separate module from this. I wasn't sure how I'd go about doing it, since you'd most likely do it different than I would. As for the licenses, I actually hadn't checked, I think [this is the Fabric license](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/LICENSE) and I also think [this is the UWP license](https://github.com/microsoft/microsoft-ui-xaml/blob/master/LICENSE).

The new VM already does make caching functions not worth your time, which is why I do `math_`. It's just a simple find all `math_` and replace with `math.` to optimize for the new VM.

**Comment by Sleitnick** [comment]
Closing this for now

**Pull request closed without merging**
